/**
 * Shared runtime utilities for scripted agent binaries (pi + hermes).
 *
 * This module exports the building blocks that both the pi and hermes
 * scripted runtimes use: prompt parsing, CLI spawning, behavior loading,
 * work-index tracking, placeholder substitution, journaling, and behavior
 * action application.
 *
 * Each runtime (scripted-agent-runtime.mjs for pi, scripted-hermes-runtime.mjs
 * for hermes) imports these functions and wires them together with its own
 * output emission (pi JSON events vs hermes plain text).
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

// ── Prompt parsing ──────────────────────────────────────────────────
//
// Both pi and hermes work prompts share the same structure generated by
// buildWorkPrompt(): a header line with "workflow X, agent Y, run Z" and
// a "path/to/tamandua" step claim command.

/**
 * Parse the work prompt to extract workflow/agent/run IDs and the CLI path.
 * Returns null if the prompt cannot be parsed.
 */
export function parsePrompt(input) {
  const header = input.match(
    /workflow "([^"]+)", agent "([^"]+)", run "([^"]+)"/,
  );
  if (!header) return null;
  const [, workflowId, agentId, runId] = header;

  const cliMatch = input.match(/(?:node )?"([^"]+)" step (?:claim|peek)/);
  if (!cliMatch) return null;
  const cliPath = cliMatch[1];

  const shortAgent = agentId.startsWith(`${workflowId}_`)
    ? agentId.slice(workflowId.length + 1)
    : agentId;

  return { workflowId, agentId, runId, cliPath, shortAgent };
}

// ── tamandua CLI invocation ──────────────────────────────────────────
//
// The prompt's CLI path may be the bin/tamandua shell launcher (exec it
// directly) or a .js entry point (run it through node). Detect by shebang
// so this works with either prompt/motor generation.

/**
 * Return a CLI spawn function bound to the given tamandua CLI path.
 * The returned function accepts (args, input?) and returns a spawnSync result.
 */
export function createCli(cliPath) {
  const isShellScript = (() => {
    try {
      const fd = fs.openSync(cliPath, "r");
      const buf = Buffer.alloc(2);
      fs.readSync(fd, buf, 0, 2, 0);
      fs.closeSync(fd);
      return buf.toString("utf-8") === "#!";
    } catch {
      return false;
    }
  })();

  const [command, baseArgs] = isShellScript
    ? [cliPath, []]
    : [process.execPath, [cliPath]];

  return (args, input) =>
    spawnSync(command, [...baseArgs, ...args], {
      encoding: "utf-8",
      cwd: process.cwd(),
      env: process.env,
      input,
      maxBuffer: 16 * 1024 * 1024,
    });
}

// ── Step CLI wrappers ───────────────────────────────────────────────

export function peekStep(cli, agentId, runId) {
  return cli(["step", "peek", agentId, "--run-id", runId]);
}

export function claimStep(cli, agentId, runId) {
  return cli(["step", "claim", agentId, "--run-id", runId]);
}

export function completeStep(cli, stepId, outputText) {
  return cli(["step", "complete", stepId], outputText);
}

export function failStep(cli, stepId, reason) {
  return cli(["step", "fail", stepId, reason]);
}

// ═══════════════════════════════════════════════════════════════════
// KNOB-REGION-BEGIN — IFLB US-007 launch-time harness probe support
// ═══════════════════════════════════════════════════════════════════

// ── Launch-time harness probe support (IFLB) ────────────────────────
//
// The dispatch motor runs a launch-time harness probe at a run's FIRST real
// dispatch (see src/installer/harness-probe.ts): the harness is asked to run
// the exact command `<launcher> skill-path` (an absolute CLI launcher path,
// never a bare `tamandua`) and reply with the PATH and nothing else. The
// probe prompt is NOT a work prompt — it has no workflow/agent/run header,
// so parsePrompt() cannot parse it and every scripted runtime would otherwise
// fatal() on it. Each runtime therefore recognizes the stable marker line
// below BEFORE parsing, executes the quoted command for real in the child
// environment, and replies with the command's stdout path.
//
// A probe answer must NOT be journaled as an invocation and must NOT consume
// the canned-behaviors invocation index: the probe is not a work round, so it
// must not disturb behaviors.json work sequencing or the invocation journal
// that scripted e2e suites assert on.

export const HARNESS_PROBE_MARKER = "TAMANDUA_HARNESS_PROBE: skill-path";

/**
 * True when the prompt is a launch-time harness probe prompt: its first line
 * is exactly the stable marker `TAMANDUA_HARNESS_PROBE: skill-path`.
 */
export function isHarnessProbePrompt(prompt) {
  const firstLine = String(prompt ?? "").split(/\r?\n/, 1)[0] ?? "";
  return firstLine.trim() === HARNESS_PROBE_MARKER;
}

/**
 * Extract the exact quoted command from a probe prompt. The daemon builds the
 * prompt as `<marker>\nRun the exact command "<launcher> skill-path" and reply
 * with the PATH and nothing else.` Returns null when the prompt is not a probe
 * prompt / does not quote a command.
 */
export function parseHarnessProbeCommand(prompt) {
  const m = String(prompt ?? "").match(
    /Run the exact command "([^"]+)" and reply with the PATH and nothing else\./,
  );
  return m ? m[1] : null;
}

/**
 * Split a probe command string into an argv array. The daemon quotes the whole
 * `<launcher> skill-path` command; the launcher is an absolute path that may
 * (in principle) contain spaces, so split quote-aware instead of on whitespace.
 */
export function splitProbeCommand(cmd) {
  const argv = [];
  let current = "";
  let inQuotes = false;
  for (const ch of String(cmd)) {
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === " " && !inQuotes) {
      if (current.length > 0) {
        argv.push(current);
        current = "";
      }
    } else {
      current += ch;
    }
  }
  if (current.length > 0) argv.push(current);
  return argv;
}

/**
 * Execute the quoted probe command for real in the child environment (the
 * same env the runtime process itself received — the daemon hands the harness
 * the identical env it uses for the daemon-side expected-value computation).
 *
 * Returns { ok, path, exitCode, signal, stderr }:
 *  - ok: the command exited 0 and produced a non-empty trimmed stdout path
 *  - path: the trimmed stdout (the PATH the harness must reply with)
 *  - exitCode / signal / stderr: child forensics for the failure reply
 *
 * Never journaled, never consumes a work index, never throws.
 */
export function execHarnessProbe(prompt) {
  const cmd = parseHarnessProbeCommand(prompt);
  if (cmd === null || cmd.length === 0) {
    return {
      ok: false,
      path: "",
      exitCode: 2,
      signal: null,
      stderr: `probe prompt did not quote a command: ${String(prompt).slice(0, 200)}`,
    };
  }
  const argv = splitProbeCommand(cmd);
  const r = spawnSync(argv[0], argv.slice(1), {
    encoding: "utf-8",
    cwd: process.cwd(),
    env: process.env,
    maxBuffer: 16 * 1024 * 1024,
  });
  const stdout = (r.stdout ?? "").trim();
  return {
    ok: r.status === 0 && stdout.length > 0,
    path: stdout,
    exitCode: r.status,
    signal: r.signal,
    stderr: (r.stderr ?? "").slice(0, 2000),
  };
}

// ═══════════════════════════════════════════════════════════════════
// KNOB-REGION-END
// ═══════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════
// KNOB-REGION-BEGIN — STORM US-002 campaign-controlled mid-flight hold
// ═══════════════════════════════════════════════════════════════════

// ── Campaign-controlled mid-flight hold ─────────────────────────────
//
// SCRIPTED_REHEARSAL runs a tiny fixture, so the scripted agent rounds would
// otherwise finish in seconds — long before any Round-B chaos phase is due
// (SF-8). To keep a roster run ACTIVE (step claimed, worker alive) while the
// engine samples the concurrency window and fires chaos, a generated scripted
// behavior may carry a `hold`:
//
//   behavior.hold = { id: "storm-midflight", timeoutMs?: <ms> }
//
// applyHold() writes `<holdDir>/<runId>.confirmed` and then blocks (async,
// never the event loop) until the campaign writes `<holdDir>/<runId>.release`.
// The hold directory resolves from an explicit `holdDir`, then
// TAMANDUA_SCRIPTED_HOLD_DIR, then `<stateDir>/holds`. The engine releases
// Round-A holds only after sampling the 8-concurrent window and releases each
// Round-B target only after its chaos phase fired — so every phase predicate
// observes a live target (requirement 1a).
//
// Fail-closed (requirement 1d): the wait is bounded by behavior.hold.timeoutMs
// (then TAMANDUA_SCRIPTED_HOLD_TIMEOUT_MS, then DEFAULT_HOLD_TIMEOUT_MS). On
// timeout we write `<holdDir>/<runId>.missed` with a JSON reason and return
// outcome 'timeout' so the run is released and the phase is marked MISSED by
// the engine. applyHold NEVER throws and NEVER blocks past the timeout.
//
// One-shot per run lifecycle (SF-10): a hold is armed at most once per
// (campaign, runId) — the run-lifecycle checkpoint (one workflow execution,
// one hold). Once a `<runId>.release` or `<runId>.missed` marker exists, a
// later invocation of ANY agent in that same run (e.g. the second merger round
// after a finalize_merge reroute, or a DRDV do-again) must NOT re-arm the hold:
// it short-circuits with outcome 'already_released' / 'already_missed',
// journaled as hold_already_released / hold_already_missed, WITHOUT writing
// `.confirmed` and WITHOUT waiting on the bound. applyHold therefore NEVER
// deletes a release/missed marker it did not write — those markers belong to
// the engine. (Before SF-10 the entry code rmSync'd both markers, so every
// later round re-armed the hold and burned the full 1800 s bound.)
//
// Honesty (requirement 1c): this is a real wait on an engine-owned checkpoint;
// there is no canned chaos-recovery fallback anywhere in the scripted runtimes —
// a killed/parked/rugpulled run must show the product's real recovery.

export const HOLD_CONFIRMED_SUFFIX = ".confirmed";
export const HOLD_RELEASE_SUFFIX = ".release";
export const HOLD_MISSED_SUFFIX = ".missed";
export const DEFAULT_HOLD_TIMEOUT_MS = 1_800_000;

// Poll cadence for the release checkpoint. Small enough that the engine's
// release is observed promptly, large enough to stay cheap for 8+ held runs.
const HOLD_POLL_INTERVAL_MS = 250;

/**
 * Resolve the campaign-owned hold directory. Priority:
 *   1. explicit `holdDir` argument
 *   2. TAMANDUA_SCRIPTED_HOLD_DIR env var
 *   3. `<stateDir>/holds`
 * Returns null when none is configured (the hold then degrades to 'skipped').
 */
export function resolveHoldDir({ holdDir, stateDir } = {}) {
  if (holdDir) return holdDir;
  if (process.env.TAMANDUA_SCRIPTED_HOLD_DIR) {
    return process.env.TAMANDUA_SCRIPTED_HOLD_DIR;
  }
  if (stateDir) return path.join(stateDir, "holds");
  return null;
}

function holdSleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, Math.max(0, ms)));
}

/**
 * Apply a campaign-controlled mid-flight hold. See the KNOB-REGION comment
 * above for the full contract.
 *
 * Returns (always, never rejects):
 *   - { attempted: false }                              no behavior.hold
 *   - { attempted: true, outcome: 'skipped', reason }   no hold dir configured
 *   - { attempted: true, outcome: 'released', ... }     release checkpoint seen
 *   - { attempted: true, outcome: 'timeout', reason }   bounded wait elapsed
 *                                                       (or any unexpected error
 *                                                       — fail-closed)
 *   - { attempted: true, outcome: 'already_released', ... } an earlier
 *                                                       invocation in this run
 *                                                       already released it
 *                                                       (SF-10 one-shot)
 *   - { attempted: true, outcome: 'already_missed', ... } an earlier
 *                                                       invocation in this run
 *                                                       already missed it
 *                                                       (SF-10 one-shot)
 */
export async function applyHold(
  behavior,
  { stateDir, holdDir, runId, log } = {},
) {
  const hold = behavior?.hold;
  if (!hold) return { attempted: false };

  const journal =
    typeof log === "function"
      ? log
      : (entry) => logInvocation(stateDir, entry);

  const dir = resolveHoldDir({ holdDir, stateDir });
  if (!dir) {
    const reason = "no hold dir configured (holdDir/env/stateDir all absent)";
    journal({ phase: "hold_skipped", runId, holdId: hold.id ?? null, note: reason });
    return { attempted: true, outcome: "skipped", reason };
  }

  const holdId = hold.id ?? "hold";
  const behaviorTimeout = Number(hold.timeoutMs);
  const envTimeout = Number(process.env.TAMANDUA_SCRIPTED_HOLD_TIMEOUT_MS);
  const timeoutMs =
    Number.isFinite(behaviorTimeout) && behaviorTimeout > 0
      ? behaviorTimeout
      : Number.isFinite(envTimeout) && envTimeout > 0
        ? envTimeout
        : DEFAULT_HOLD_TIMEOUT_MS;

  const confirmedPath = path.join(dir, `${runId}${HOLD_CONFIRMED_SUFFIX}`);
  const releasePath = path.join(dir, `${runId}${HOLD_RELEASE_SUFFIX}`);
  const missedPath = path.join(dir, `${runId}${HOLD_MISSED_SUFFIX}`);

  // ── SF-10 one-shot rule ──────────────────────────────────────────
  // A hold is armed at most once per (campaign, runId). If the engine has
  // already released or missed this run, a later invocation of any agent in
  // the same run must not re-arm it: return immediately without writing
  // `.confirmed`, without waiting, and WITHOUT deleting the engine's marker.
  // Checked before mkdir/write so an existing marker is never touched.
  if (fs.existsSync(releasePath)) {
    journal({ phase: "hold_already_released", runId, holdId, holdDir: dir });
    return { attempted: true, outcome: "already_released", holdId, holdDir: dir };
  }
  if (fs.existsSync(missedPath)) {
    journal({ phase: "hold_already_missed", runId, holdId, holdDir: dir });
    return { attempted: true, outcome: "already_missed", holdId, holdDir: dir };
  }

  const failClosed = (reason) => {
    const missed = { runId, holdId, reason, ts: new Date().toISOString() };
    try {
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(missedPath, JSON.stringify(missed) + "\n", "utf-8");
    } catch {
      // never let diagnostics block the fail-closed return
    }
    journal({ phase: "hold_timeout", runId, holdId, reason });
    return { attempted: true, outcome: "timeout", reason };
  };

  try {
    fs.mkdirSync(dir, { recursive: true });

    // No stale-marker cleanup here: the one-shot checks above already returned
    // when a release/missed marker existed, and deleting a marker we did not
    // write would re-arm the hold for a later round (SF-10).
    fs.writeFileSync(
      confirmedPath,
      JSON.stringify({ runId, holdId, ts: new Date().toISOString() }) + "\n",
      "utf-8",
    );
    journal({ phase: "hold_wait", runId, holdId, holdDir: dir, timeoutMs });

    const deadline = Date.now() + timeoutMs;
    for (;;) {
      if (fs.existsSync(releasePath)) {
        journal({ phase: "hold_released", runId, holdId, how: "release" });
        return { attempted: true, outcome: "released", holdId, holdDir: dir };
      }
      if (Date.now() >= deadline) {
        return failClosed(
          `hold timed out after ${timeoutMs}ms without a release checkpoint`,
        );
      }
      const remaining = deadline - Date.now();
      await holdSleep(Math.min(HOLD_POLL_INTERVAL_MS, Math.max(1, remaining)));
    }
  } catch (err) {
    return failClosed(
      `hold error: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

// ═══════════════════════════════════════════════════════════════════
// KNOB-REGION-END
// ═══════════════════════════════════════════════════════════════════

// ── Behaviors config ────────────────────────────────────────────────

const DEFAULT_CONFIG = { agents: {}, heartbeatTokens: 17, defaultTokens: 111 };

/**
 * Load behaviors config from a JSON file. Returns default config if the
 * file doesn't exist.
 */
export function loadBehaviors(behaviorsPath) {
  const config = { ...DEFAULT_CONFIG };
  if (behaviorsPath && fs.existsSync(behaviorsPath)) {
    Object.assign(config, JSON.parse(fs.readFileSync(behaviorsPath, "utf-8")));
  }
  return config;
}

/**
 * Look up the behavior for an agent at a given work index.
 * An array is consumed one entry per invocation, last entry repeating.
 * Full workflowId_agentId key takes priority; shortAgent is fallback for
 * backward compatibility with existing behavior files.
 */
export function behaviorForInvocation(config, agentId, shortAgent, index) {
  const entry = config.agents[agentId] ?? config.agents[shortAgent];
  if (entry === undefined) return undefined;
  const list = Array.isArray(entry) ? entry : [entry];
  if (list.length === 0) return undefined;
  return list[Math.min(index, list.length - 1)];
}

/**
 * Increment and return the invocation count for a keyed agent.
 * The count is persisted in stateDir/<key>.workcount.
 *
 * Uses a file-based mutex (mkdirSync) to serialize access across
 * concurrent harness processes, so 8 simultaneous runs each get
 * a unique behavior index without races. The lock directory is
 * removed after each increment — no leaked .lock files in normal
 * operation.
 */
export function nextWorkIndex(stateDir, key) {
  const countFile = path.join(stateDir, `${key}.workcount`);
  const lockDir = path.join(stateDir, `${key}.workcount.lock`);

  // Exponential-backoff file-system mutex.
  // mkdirSync without {recursive:true} throws EEXIST if the
  // directory already exists — atomic on both macOS and Linux.
  const maxRetries = 50;
  const baseDelayMs = 2;
  const maxDelayMs = 10;

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      fs.mkdirSync(lockDir);
      break; // lock acquired
    } catch (err) {
      if (err.code !== "EEXIST") throw err;
      if (attempt === maxRetries - 1) {
        throw new Error(
          `Could not acquire lock for ${key} after ${maxRetries} attempts`,
        );
      }
      // Exponential backoff with 10 % jitter to avoid thundering herd.
      const delay = Math.min(baseDelayMs * Math.pow(2, attempt), maxDelayMs);
      const jittered = delay + Math.random() * delay * 0.1;
      const start = Date.now();
      while (Date.now() - start < jittered) {
        // busy-wait
      }
    }
  }

  try {
    // Read + write inside the lock — both operations serialized.
    fs.mkdirSync(stateDir, { recursive: true });
    let count = 0;
    try {
      count = parseInt(fs.readFileSync(countFile, "utf-8"), 10) || 0;
    } catch {
      // first invocation
    }
    fs.writeFileSync(countFile, String(count + 1), "utf-8");
    return count;
  } finally {
    // Release lock: remove the lock directory.
    try {
      fs.rmdirSync(lockDir);
    } catch (err) {
      if (err.code !== "ENOENT") throw err;
    }
  }
}

// ── Placeholder substitution ────────────────────────────────────────
// {{cwd}} → workdir; {{gitTree}} → current HEAD tree; {{input.KEY}} → input

/**
 * Parse KEY: value lines from a step input string.
 */
export function parseInputVars(input) {
  const vars = {};
  for (const line of input.split(/\r?\n/)) {
    const m = line.match(/^([A-Z][A-Z0-9_]*):\s*(.*)$/);
    if (m) vars[m[1]] = m[2].trim();
  }
  return vars;
}

/**
 * Substitute {{cwd}}, {{gitTree}}, and {{input.KEY}} placeholders in text.
 * Throws if a referenced KEY is missing from inputVars.
 */
export function substitute(text, cwd, inputVars) {
  let rendered = text.replaceAll("{{cwd}}", cwd);
  if (rendered.includes("{{gitTree}}")) {
    const tree = spawnSync("git", ["rev-parse", "HEAD^{tree}"], {
      cwd,
      encoding: "utf-8",
      env: process.env,
    });
    if (tree.status !== 0 || !tree.stdout.trim()) {
      throw new Error(`could not resolve git tree in ${cwd}: ${tree.stderr.trim()}`);
    }
    rendered = rendered.replaceAll("{{gitTree}}", tree.stdout.trim());
  }
  return rendered
    .replace(/\{\{input\.([A-Za-z0-9_]+)\}\}/g, (_, key) => {
      const upper = key.toUpperCase();
      if (!(upper in inputVars)) {
        throw new Error(
          `no "${upper}:" line in step input for placeholder {{input.${key}}}`,
        );
      }
      return inputVars[upper];
    });
}

// ── Journaling ──────────────────────────────────────────────────────

/**
 * Append a JSON line to stateDir/invocations.jsonl.
 * Never throws — silently drops on any failure.
 */
export function logInvocation(stateDir, entry) {
  if (!stateDir) return;
  try {
    fs.mkdirSync(stateDir, { recursive: true });
    fs.appendFileSync(
      path.join(stateDir, "invocations.jsonl"),
      JSON.stringify({
        ts: new Date().toISOString(),
        pid: process.pid,
        ...entry,
      }) + "\n",
      "utf-8",
    );
  } catch {
    // never let diagnostics kill the round
  }
}

/**
 * Log an error and exit. label distinguishes the runtime (e.g. "scripted-agent"
 * vs "scripted-hermes") in stderr messages.
 */
export function fatal(stateDir, label, note, exitCode = 1) {
  logInvocation(stateDir, { phase: "error", note });
  process.stderr.write(`${label}: ${note}\n`);
  process.exit(exitCode);
}

// ── Behavior action application ─────────────────────────────────────

/**
 * Apply scripted behavior actions (edits, writes, commands) in the given
 * working directory. Throws on any failure — callers should catch and
 * turn the error into a step fail report.
 */
export function applyBehaviorActions(behavior, cwd, inputVars) {
  const commandOutputs = [];
  for (const edit of behavior.edits ?? []) {
    const filePath = path.resolve(cwd, substitute(edit.file, cwd, inputVars));
    const content = fs.readFileSync(filePath, "utf-8");
    const find = substitute(edit.find, cwd, inputVars);
    if (!content.includes(find)) {
      throw new Error(
        `scripted edit: pattern not found in ${edit.file}: ${find}`,
      );
    }
    fs.writeFileSync(
      filePath,
      content.replaceAll(find, substitute(edit.replace, cwd, inputVars)),
      "utf-8",
    );
  }
  for (const write of behavior.writes ?? []) {
    const filePath = path.resolve(cwd, substitute(write.file, cwd, inputVars));
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(
      filePath,
      substitute(write.content, cwd, inputVars),
      "utf-8",
    );
  }
  for (const command of behavior.commands ?? []) {
    const rendered = substitute(command, cwd, inputVars);
    const r = spawnSync("bash", ["-c", rendered], {
      cwd,
      encoding: "utf-8",
      env: process.env,
      maxBuffer: 16 * 1024 * 1024,
    });
    if (r.status !== 0) {
      throw new Error(
        `scripted command failed (exit ${r.status}): ${rendered}\n${r.stderr}`,
      );
    }
    const stdout = r.stdout.trimEnd();
    if (stdout) commandOutputs.push(stdout);
  }
  return { commandOutput: commandOutputs.join("\n") };
}
