// US-001 (MACP2) — tt-python / tt-python@master builders seed deterministic
// synthetic __pycache__ junk (a provisioning artifact, not an interpreter side
// effect).
//
// Apple's Python bakes in sys.pycache_prefix = ~/Library/Caches/com.apple.python,
// so bytecode caches are ALWAYS redirected out-of-tree on Darwin — in-tree
// __pycache__ can never be relied on (verified live: plain import + compileall
// produce no in-tree __pycache__; dont_write_bytecode is False). The old
// tt-python@master builder asserted in-tree __pycache__ exists after the test
// run, which can never pass on macOS. US-001 fixes this architecturally, per the
// E2.4 operator-notes.local precedent: the junk is a DETERMINISTIC PROVISIONING
// ARTIFACT — a tracked byte-exact reference in fixtures-src/ that the builder
// seeds into its scratch clone BEFORE the test run and then asserts present +
// untracked + byte-identical.
//
// This test pins the US-001 acceptance criteria with zero tokens and no golden
// rebuild required:
//   AC1: the byte-exact reference fixtures-src/tt-python/__pycache__/
//        junk-probe.synthetic exists, is non-empty, is TRACKED (git ls-files
//        shows it), and is NOT gitignored.
//   AC2: BOTH tt-python and tt-python@master build-golden.sh seed the
//        reference into the scratch clone (mkdir -p __pycache__ + cp from
//        $FIXTURE_SRC/__pycache__/junk-probe.synthetic) BEFORE the junk-probe
//        test run and assert the seeded junk is (1) present, (2) untracked via
//        git ls-files --error-unmatch, (3) byte-identical via cmp.
//   AC3: NO builder assertion depends on the interpreter having generated
//        in-tree __pycache__ (the old `[ ! -d "__pycache__" ]` presence check
//        and "not found after test run" phrasing are gone); .pytest_cache
//        (regenerated by pytest itself, Darwin-safe) and operator-notes.local
//        checks remain.
//   AC4: the reference filename never collides with an importable module name
//        (CPython never tries to read it as bytecode).
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { describe, it } from "node:test";

const repoRoot = process.cwd();
const ttRoot = path.join(repoRoot, "torture-test");
const fixturesSrc = path.join(ttRoot, "fixtures-src");

const JUNK_REF = path.join(
  fixturesSrc,
  "tt-python",
  "__pycache__",
  "junk-probe.synthetic",
);

const BUILDERS = [
  "tt-python/build-golden.sh",
  "tt-python@master/build-golden.sh",
];

function readBuilder(rel: string): string {
  return fs.readFileSync(path.join(fixturesSrc, rel), "utf8");
}

describe("US-001 MACP2 builder junk seeding (deterministic synthetic __pycache__)", () => {
  it("AC1: the byte-exact reference exists, is non-empty, tracked, and not gitignored", () => {
    assert.ok(fs.existsSync(JUNK_REF), `reference missing: ${JUNK_REF}`);
    assert.ok(fs.statSync(JUNK_REF).isFile(), "reference must be a file");
    assert.ok(fs.statSync(JUNK_REF).size > 0, "reference must be non-empty");

    // Tracked in git: git ls-files --error-unmatch succeeds.
    const ls = spawnSync(
      "git",
      ["ls-files", "--error-unmatch", "torture-test/fixtures-src/tt-python/__pycache__/junk-probe.synthetic"],
      { cwd: repoRoot, encoding: "utf8" },
    );
    assert.equal(ls.status, 0, "reference must be tracked in git (git ls-files --error-unmatch)");

    // NOT gitignored: git check-ignore must fail.
    const ci = spawnSync(
      "git",
      ["check-ignore", "-q", "torture-test/fixtures-src/tt-python/__pycache__/junk-probe.synthetic"],
      { cwd: repoRoot, encoding: "utf8" },
    );
    assert.notEqual(ci.status, 0, "reference must NOT be gitignored");
  });

  it("AC2: both builders seed the reference into the scratch clone BEFORE the test run and assert present + untracked + byte-identical", () => {
    for (const rel of BUILDERS) {
      const src = readBuilder(rel);
      // Seeding: mkdir -p __pycache__ + cp from the fixtures-src reference.
      assert.ok(
        /JUNK_REF="\$FIXTURE_SRC\/__pycache__\/junk-probe\.synthetic"/.test(src),
        `${rel} must bind JUNK_REF to the fixtures-src reference`,
      );
      assert.ok(
        /mkdir -p "\$SCRATCH_DIR\/__pycache__"/.test(src) ||
          /mkdir -p "__pycache__"/.test(src),
        `${rel} must mkdir -p the scratch-clone __pycache__ dir`,
      );
      assert.ok(
        /cp "\$JUNK_REF" "\$SCRATCH_DIR\/__pycache__\/junk-probe\.synthetic"/.test(src),
        `${rel} must cp the reference into the scratch clone`,
      );
      // Seeding must come BEFORE the junk-probe test run.
      const seedIdx = src.indexOf('cp "$JUNK_REF"');
      const runIdx = src.indexOf("junk-probe test run failed");
      assert.ok(
        seedIdx >= 0 && runIdx >= 0 && seedIdx < runIdx,
        `${rel}: seeding must happen BEFORE the junk-probe test run`,
      );

      // Assertions: present (file check), untracked (ls-files --error-unmatch
      // must FAIL), byte-identical (cmp -s against the reference).
      assert.ok(
        /-f "__pycache__\/junk-probe\.synthetic"/.test(src),
        `${rel} must assert the seeded marker is PRESENT`,
      );
      assert.ok(
        /git ls-files --error-unmatch __pycache__\/junk-probe\.synthetic/.test(src),
        `${rel} must assert UNTRACKED via git ls-files --error-unmatch`,
      );
      assert.ok(
        /cmp -s "\$JUNK_REF" "__pycache__\/junk-probe\.synthetic"/.test(src),
        `${rel} must assert BYTE-IDENTICAL via cmp against the reference`,
      );
    }
  });

  it("AC3: no builder asserts interpreter-generated in-tree __pycache__; .pytest_cache + operator-notes checks remain", () => {
    for (const rel of BUILDERS) {
      const src = readBuilder(rel);
      // The old interpreter-dependence presence check must be gone.
      assert.ok(
        !/[^e]\[ ! -d "__pycache__" \]/.test(src),
        `${rel}: interpreter-dependence check '[ ! -d "__pycache__" ]' must be removed`,
      );
      assert.ok(
        !src.includes('"✗ __pycache__/ not found after test run"'),
        `${rel}: 'not found after test run' presence phrasing must be gone`,
      );
      // Darwin-safe regenerated junk (.pytest_cache) + operator-notes checks remain.
      assert.ok(
        src.includes("✗ .pytest_cache/ not found after test run"),
        `${rel} must keep the .pytest_cache presence check`,
      );
      assert.ok(
        /git ls-files --error-unmatch \.pytest_cache/.test(src),
        `${rel} must keep the .pytest_cache untracked check`,
      );
      assert.ok(
        src.includes("operator-notes.local"),
        `${rel} must keep the operator-notes.local checks`,
      );
    }
  });

  it("AC4: the reference filename can never collide with an importable module name", () => {
    // CPython reads __pycache__/<module>.<magic>.pyc for modules it imports.
    // A filename that (a) is not `<module>.cpython-*.pyc` shaped and (b) is not
    // a valid Python identifier cannot be read as bytecode.
    const name = path.basename(JUNK_REF); // junk-probe.synthetic
    assert.ok(!name.endsWith(".pyc"), "marker filename must not look like a pyc module artifact");
    assert.ok(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name), "marker filename must not be a valid module identifier");
    assert.ok(name.includes("-"), "marker filename must carry a non-identifier char (hyphen)");
  });
});
