// Tier-0 integration gate (US-004): controller predicates against the REAL
// host-profile produced by tt-verify-environment on this machine.
//
// Regression net for E2.2: case predicates and the W0.0 host-profile schema
// were never integration-tested against each other, so an --include-real
// campaign was vacuously GREEN with every real Tier-1 case blocked NOT_RUN
// (predicate). This file exercises the controller's predicate evaluator
// (applyHostRequirements -> evaluateRequirements -> observedCapability)
// against the real `var/w0/host-profile.json` generated by tt-verify-environment
// for EVERY tier1 real case's `requires`, plus an honestly-absent capability.
//
// Zero-token by construction: tt-verify-environment runs with --fast (no
// --spend, no live harness auth), every tier1 case is evaluated through a
// `local`/scripted manifest (no pi/hermes model invocation), and the
// independent oracle below verifies the controller's verdicts. No model is
// ever launched.
//
// The oracle in this file is intentionally INDEPENDENT of the controller: it
// re-reads the canonical boolean-leaf contract from the profile so a green
// result is meaningful (the controller agrees with an independently-computed
// satisfaction verdict), and a divergent controller is caught.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, it } from "node:test";

const repoRoot = process.cwd();
const ttRoot = path.join(repoRoot, "torture-test");
const binDir = path.join(ttRoot, "bin");
const verifyEnv = path.join(binDir, "tt-verify-environment");
const controller = path.join(binDir, "tt-controller");
const varRoot = path.join(ttRoot, "var");
const hostProfilePath = path.join(varRoot, "w0", "host-profile.json");

const CAMPAIGN_LINE = /^Campaign:\s+(campaign-[^\s]+)$/m;
const ABSENT_CAP_ID = "US004-ABSENT-CAP";

interface RunResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

function runTt(script: string, args: string[]): RunResult {
  const res = spawnSync(process.execPath, [script, ...args], {
    cwd: ttRoot,
    encoding: "utf8",
    timeout: 300_000,
    env: { ...process.env, HOME: os.homedir() },
  });
  return {
    status: res.status,
    stdout: String(res.stdout ?? ""),
    stderr: String(res.stderr ?? ""),
  };
}

function loadJson(file: string): any {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

// ── Independent canonical-contract oracle ──────────────────────────────
// Satisfied iff the profile records the boolean leaf required by the
// documented host-adaptation contract (see cases/case.schema.json requires.*
// and spec 01). Does NOT call the controller.
function requiresSatisfiedByProfile(requires: any, profile: any): boolean {
  const req = requires ?? {};
  if (req.platform !== undefined) {
    const allowed = Array.isArray(req.platform) ? req.platform : [req.platform];
    if (!allowed.includes(profile.platform?.os)) return false;
  }
  for (const name of req.toolchains ?? []) {
    if (profile.toolchains?.[name]?.present !== true) return false;
  }
  for (const name of req.containment ?? []) {
    const value = profile.containment?.[name];
    if (name === "procfs") {
      if (value !== true && profile.capabilities?.procfs !== true) return false;
    } else if (value !== true) {
      return false;
    }
  }
  if (req.node_min !== undefined) {
    const majors = (profile.nodeRuntimes ?? [])
      .map((r: any) => r.major)
      .filter((m: any) => Number.isSafeInteger(m) && m >= 0);
    if (majors.length === 0 || Math.max(...majors) < req.node_min) return false;
  }
  for (const name of req.capabilities ?? []) {
    let ok = false;
    if (name === "pi" || name === "hermes") {
      ok = profile.harness?.[name]?.present === true;
    } else if (name === "node-sqlite") {
      ok = (profile.nodeRuntimes ?? []).some((r: any) => r.sqliteAvailable === true);
    } else if (name === "procfs") {
      ok = profile.containment?.procfs === true || profile.capabilities?.procfs === true;
    } else if (name === "systemd-user-scope") {
      ok = profile.containment?.systemdUserScope === true;
    } else {
      ok = profile.capabilities?.[name] === true;
    }
    if (!ok) return false;
  }
  return true;
}

// Build and WRITE a zero-token manifest under var/: every tier1 REAL case
// copied VERBATIM (id + requires), but executed through a `local`/scripted
// env (no pi/hermes model) so the controller runs its predicate phase
// (applyHostRequirements) without launching anything. Plus one case requiring
// an honestly-absent capability. Returns the manifest path.
function buildManifest(): string {
  const tier1Path = path.join(ttRoot, "cases", "tier1.jsonl");
  const tier1: any[] = fs
    .readFileSync(tier1Path, "utf8")
    .split(/\r?\n/)
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line));

  const real = tier1.filter((c) => !c.scripted);
  assert.ok(real.length > 0, "tier1.jsonl must contain real (non-scripted) cases");
  const records: any[] = real.map((c) => ({
    id: c.id,
    wave: 1,
    workflow: "local",
    fixture: "none",
    harness: "local",
    task: `cases/tasks/tier1/${c.id}.md`,
    context: { execution_mode: "scripted" },
    caps: { tokens: 0, wall_min: 5 },
    requires: c.requires ?? {},
    boundary_files: [],
    forbidden: [],
    oracles: [],
    gates: [],
    chaos: null,
    shed_ok: false,
    mandatory: true,
    class: "verification",
    reset: { executable: "node", args: ["-e", "process.exit(0)"], cwd: "." },
    command: {
      executable: "node",
      args: [
        "-e",
        "console.log(JSON.stringify({status:'done'}));process.exit(0)",
      ],
      cwd: ".",
    },
  }));

  // Honestly-absent capability: not recorded anywhere on this host, so it must
  // gate NOT_RUN (predicate) with evidence rather than launch or skip.
  records.push({
    id: ABSENT_CAP_ID,
    wave: 1,
    workflow: "local",
    fixture: "none",
    harness: "local",
    task: "cases/tasks/tier1/W1.L1-ts.md",
    context: { execution_mode: "scripted" },
    caps: { tokens: 0, wall_min: 5 },
    requires: {
      toolchains: ["node"],
      capabilities: ["definitely-not-a-real-capability"],
      node_min: 22,
    },
    boundary_files: [],
    forbidden: [],
    oracles: [],
    gates: [],
    chaos: null,
    shed_ok: false,
    mandatory: true,
    class: "verification",
    reset: { executable: "node", args: ["-e", "process.exit(0)"], cwd: "." },
    command: {
      executable: "node",
      args: ["-e", "console.log(JSON.stringify({status:'done'}));process.exit(0)"],
      cwd: ".",
    },
  });

  const name = `US004-${Date.now()}-${process.pid}.jsonl`;
  const manifestPath = path.join(varRoot, name);
  fs.writeFileSync(manifestPath, `${records.map((r) => JSON.stringify(r)).join("\n")}\n`);
  return manifestPath;
}

describe("Controller predicates against the REAL host-profile (US-004)", () => {
  it("tt-verify-environment --fast produces the real host-profile and records pi/hermes presence (no silent skip)", () => {
    const res = runTt(verifyEnv, ["--fast", "--json"]);
    assert.equal(res.status, 0, `tt-verify-environment failed:\n${res.stderr}${res.stdout}`);
    assert.ok(fs.existsSync(hostProfilePath), "host-profile.json must be written by tt-verify-environment");
    const profile = loadJson(hostProfilePath);
    // AC4: presence must be recorded as a boolean leaf, never silently dropped.
    const piPresent = profile.harness?.pi?.present;
    const hermesPresent = profile.harness?.hermes?.present;
    assert.equal(typeof piPresent, "boolean", "host-profile must record harness.pi.present");
    assert.equal(typeof hermesPresent, "boolean", "host-profile must record harness.hermes.present");
    // On this operator-preconfigured machine pi and hermes resolve, so real
    // harness Tier-1 cases are honestly admissible here.
    assert.equal(piPresent, true, "pi is present on this host; profile must record it truthfully");
    assert.equal(hermesPresent, true, "hermes is present on this host; profile must record it truthfully");
    for (const tc of ["python3", "node"]) {
      assert.equal(typeof profile.toolchains?.[tc]?.present, "boolean",
        `profile must record toolchains.${tc}.present as a boolean leaf`);
    }
  });

  it("every tier1 real case with honestly-present requires is NOT predicate-blocked by the controller", () => {
    const resVerify = runTt(verifyEnv, ["--fast", "--json"]);
    assert.equal(resVerify.status, 0, `host-profile generation failed:\n${resVerify.stderr}`);
    const profile = loadJson(hostProfilePath);

    const manifestPath = buildManifest();
    const rel = path.relative(ttRoot, manifestPath);

    let controllerRes!: RunResult;
    let campaignId: string | null = null;
    try {
      controllerRes = runTt(controller, ["--manifest", rel]);
      const m = CAMPAIGN_LINE.exec(controllerRes.stdout);
      campaignId = m === null ? null : m[1];
    } finally {
      fs.rmSync(manifestPath, { force: true });
    }
    assert.ok(campaignId, `controller did not create a campaign:\n${controllerRes.stdout}${controllerRes.stderr}`);

    const statePath = path.join(varRoot, "results", campaignId, "state.json");
    assert.ok(fs.existsSync(statePath), `campaign state not found: ${statePath}`);
    const state = loadJson(statePath);

    // id -> requires from the ORIGINAL tier1 manifest (the manifest we ran is
    // a zero-token local copy that preserves these requires verbatim).
    const requiresByRealId = new Map<string, any>();
    fs.readFileSync(path.join(ttRoot, "cases", "tier1.jsonl"), "utf8")
      .split(/\r?\n/)
      .filter((line) => line.trim().length > 0)
      .map((line) => JSON.parse(line))
      .forEach((c: any) => requiresByRealId.set(c.id, c.requires ?? {}));

    const blocked: string[] = [];
    let assessed = 0;
    for (const caseState of state.cases) {
      const id = caseState.id;
      if (id === ABSENT_CAP_ID) continue;
      if (!requiresByRealId.has(id)) continue;
      const record = requiresByRealId.get(id)!;
      const honestlySatisfied = requiresSatisfiedByProfile(record, profile);
      if (!honestlySatisfied) {
        // Honestly-absent: assert the controller honestly gates it (AC3),
        // never silently skips or wrongly launches it.
        assert.equal(caseState.outcome, "NOT_RUN",
          `${id}: honestly-absent capability must be NOT_RUN, got outcome=${caseState.outcome}`);
        assert.equal(caseState.reason?.category, "predicate",
          `${id}: honestly-absent capability must be gated category=predicate`);
        assert.ok(caseState.reason?.evidence && caseState.reason.evidence.length > 0,
          `${id}: predicate block must carry non-empty evidence`);
        continue;
      }
      assessed += 1;
      const reason = caseState.reason ?? {};
      if (caseState.outcome === "NOT_RUN" && reason.category === "predicate") {
        blocked.push(`${id}: ${JSON.stringify(reason.evidence)}`);
      }
    }

    // Every tier1 real case on this host is honestly satisfied (python3, node,
    // node-sqlite, linux, pi, hermes all present).
    assert.ok(assessed > 0, "expected at least one honestly-satisfied tier1 real case to be assessed");
    assert.deepEqual(blocked, [],
      `controller predicate-blocked tier1 real case(s) whose requires are honestly present: ${blocked.join("; ")}`);

    fs.rmSync(path.join(varRoot, "results", campaignId), { recursive: true, force: true });
  });

  it("an honestly-absent capability yields NOT_RUN(predicate) with non-empty evidence, not a launch or silent skip", () => {
    const resVerify = runTt(verifyEnv, ["--fast", "--json"]);
    assert.equal(resVerify.status, 0, `host-profile generation failed:\n${resVerify.stderr}`);

    const manifestPath = buildManifest();
    const rel = path.relative(ttRoot, manifestPath);

    let controllerRes!: RunResult;
    let campaignId: string | null = null;
    try {
      controllerRes = runTt(controller, ["--manifest", rel]);
      const m = CAMPAIGN_LINE.exec(controllerRes.stdout);
      campaignId = m === null ? null : m[1];
    } finally {
      fs.rmSync(manifestPath, { force: true });
    }
    assert.ok(campaignId, `controller did not create a campaign:\n${controllerRes.stdout}${controllerRes.stderr}`);

    const statePath = path.join(varRoot, "results", campaignId, "state.json");
    const state = loadJson(statePath);
    const caseState = state.cases.find((c: any) => c.id === ABSENT_CAP_ID);
    assert.ok(caseState, `synthetic absent-capability case ${ABSENT_CAP_ID} not present in campaign state`);
    assert.equal(caseState.outcome, "NOT_RUN", "absent capability must yield outcome NOT_RUN");
    assert.equal(caseState.reason?.category, "predicate", "absent capability must be gated category=predicate");
    assert.ok(Array.isArray(caseState.reason?.evidence) && caseState.reason.evidence.length > 0,
      "predicate block must carry non-empty evidence");
    const evidence = caseState.reason.evidence[0];
    assert.match(String(evidence.predicate), /capabilities\.definitely-not-a-real-capability/,
      "evidence must name the absent capability predicate");
    assert.notEqual(evidence.observed, true,
      "evidence must record an honest observed value for the absent capability");

    fs.rmSync(path.join(varRoot, "results", campaignId), { recursive: true, force: true });
  });
});
